# This file is part of easy-drf.
# https://github.com/talp101/easy-drf.git

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Tal Peretz <13@1500.co.il>

language: python

python:
    - "2.7"
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
